# -*- coding: utf-8 -*-
"""palindrome.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A2hLNf2AxRL-PxUaE4doCjCc1kmEEtR2
"""

def is_palindrome(n):
  """Checks if a number is a palindrome."""
  return str(n) == str(n)[::-1]

# Example usage
number = 121
if is_palindrome(number):
  print(f"{number} is a palindrome.")
else:
  print(f"{number} is not a palindrome.")

number = 123
if is_palindrome(number):
  print(f"{number} is a palindrome.")
else:
  print(f"{number} is not a palindrome.")